kindFramework.constant('ERROR_CODE', {
	ErrorCode: {
		VALID:1,
		INVALID_PRESET:2,
		INVALID_DWELL:3,
		INVALID_NEED_TO_SET:4,
		INVALID_MAX_PRESET:5,
		INVALID_GROUP_SETTING:6,
        INVALID_JUST_RELOAD:7,
	}
})